// <auto-generated />
using System;
using LobbyistRehaulwithReact.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LobbyistRehaulwithReact.Migrations
{
    [DbContext(typeof(LobbyistDbContext))]
    [Migration("20230803191415_Add_Expenditure_Report_Table")]
    partial class Add_Expenditure_Report_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LobbyistRehaulwithReact.Models.Issues2", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("Active");

                    b.Property<string>("AssociatedProject")
                        .HasColumnType("char")
                        .HasColumnName("Associated Project");

                    b.Property<string>("Board")
                        .HasColumnType("char")
                        .HasColumnName("Board");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("Date");

                    b.Property<string>("Memo_Field")
                        .HasColumnType("char")
                        .HasColumnName("Memo_Field");

                    b.Property<string>("Principal_ID")
                        .IsRequired()
                        .HasColumnType("char")
                        .HasColumnName("Principal_ID");

                    b.HasKey("ID");

                    b.ToTable("Issues2");
                });

            modelBuilder.Entity("LobbyistRehaulwithReact.Models.Lobbyists_new", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("char")
                        .HasColumnName("Address");

                    b.Property<string>("BuesinessName")
                        .IsRequired()
                        .HasColumnType("char")
                        .HasColumnName("Business_Name");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("char")
                        .HasColumnName("City");

                    b.Property<int?>("LobbyistID")
                        .HasColumnType("int")
                        .HasColumnName("Lobbyist ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("char")
                        .HasColumnName("Name");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("char")
                        .HasColumnName("Zip_Code");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("char")
                        .HasColumnName("State");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("char")
                        .HasColumnName("Street_Address");

                    b.Property<string>("TelephoneNumber")
                        .IsRequired()
                        .HasColumnType("char")
                        .HasColumnName("Telephone_Number");

                    b.HasKey("ID");

                    b.ToTable("Lobbyists_new");
                });

            modelBuilder.Entity("LobbyistRehaulwithReact.Models.MasterList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("AssociatedProject")
                        .HasColumnType("char")
                        .HasColumnName("Associated Project");

                    b.Property<string>("LawFirmEmployeer")
                        .HasColumnType("char")
                        .HasColumnName("Law Firm/Employeer");

                    b.Property<string>("Lobbyist")
                        .IsRequired()
                        .HasColumnType("char")
                        .HasColumnName("Lobbyist");

                    b.Property<string>("LobbyistAdd")
                        .HasColumnType("char")
                        .HasColumnName("Lobbyist Add");

                    b.Property<int>("LobbyistID")
                        .HasColumnType("int")
                        .HasColumnName("Lobbyist ID");

                    b.Property<string>("LobbyistPhone")
                        .HasColumnType("char")
                        .HasColumnName("Lobbyist Phone");

                    b.Property<string>("PrincipalAdd")
                        .HasColumnType("char")
                        .HasColumnName("Principal Add");

                    b.Property<string>("PrincipalPhone")
                        .HasColumnType("char")
                        .HasColumnName("Principal Phone");

                    b.Property<int>("Principal_ID")
                        .HasColumnType("int")
                        .HasColumnName("Principal_ID");

                    b.Property<string>("Withdrawal")
                        .HasColumnType("char")
                        .HasColumnName("Withdrawal");

                    b.Property<decimal?>("amountPaid")
                        .HasColumnType("money")
                        .HasColumnName("Amount Paid");

                    b.Property<DateTime?>("dateOfPayment")
                        .HasColumnType("datetime")
                        .HasColumnName("Date of payment");

                    b.Property<string>("issue")
                        .HasColumnType("char")
                        .HasColumnName("Issue");

                    b.Property<string>("linkToApplication")
                        .HasColumnType("char")
                        .HasColumnName("Link to Application");

                    b.Property<string>("principal")
                        .HasColumnType("char")
                        .HasColumnName("Principal");

                    b.Property<string>("principleEmail")
                        .HasColumnType("char")
                        .HasColumnName("Principal Email");

                    b.Property<double?>("year")
                        .HasColumnType("float")
                        .HasColumnName("Year");

                    b.HasKey("ID");

                    b.ToTable("MasterList");
                });
#pragma warning restore 612, 618
        }
    }
}
