// <auto-generated />
using System;
using LobbyistRehaulwithReact.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LobbyistRehaulwithReact.Migrations
{
    [DbContext(typeof(LobbyistDbContext))]
    [Migration("20230803161620_Add_Issues2_Table")]
    partial class Add_Issues2_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LobbyistRehaulwithReact.Models.MasterList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("AssociatedProject")
                        .HasColumnType("char")
                        .HasColumnName("Associated Project");

                    b.Property<string>("LawFirmEmployeer")
                        .HasColumnType("char")
                        .HasColumnName("Law Firm/Employeer");

                    b.Property<string>("Lobbyist")
                        .IsRequired()
                        .HasColumnType("char")
                        .HasColumnName("Lobbyist");

                    b.Property<string>("LobbyistAdd")
                        .HasColumnType("char")
                        .HasColumnName("Lobbyist Add");

                    b.Property<int>("LobbyistID")
                        .HasColumnType("int")
                        .HasColumnName("Lobbyist ID");

                    b.Property<string>("LobbyistPhone")
                        .HasColumnType("char")
                        .HasColumnName("Lobbyist Phone");

                    b.Property<string>("PrincipalAdd")
                        .HasColumnType("char")
                        .HasColumnName("Principal Add");

                    b.Property<string>("PrincipalPhone")
                        .HasColumnType("char")
                        .HasColumnName("Principal Phone");

                    b.Property<int>("Principal_ID")
                        .HasColumnType("int")
                        .HasColumnName("Principal_ID");

                    b.Property<string>("Withdrawal")
                        .HasColumnType("char")
                        .HasColumnName("Withdrawal");

                    b.Property<decimal?>("amountPaid")
                        .HasColumnType("money")
                        .HasColumnName("Amount Paid");

                    b.Property<DateTime?>("dateOfPayment")
                        .HasColumnType("datetime")
                        .HasColumnName("Date of payment");

                    b.Property<string>("issue")
                        .HasColumnType("char")
                        .HasColumnName("Issue");

                    b.Property<string>("linkToApplication")
                        .HasColumnType("char")
                        .HasColumnName("Link to Application");

                    b.Property<string>("principal")
                        .HasColumnType("char")
                        .HasColumnName("Principal");

                    b.Property<string>("principleEmail")
                        .HasColumnType("char")
                        .HasColumnName("Principal Email");

                    b.Property<double?>("year")
                        .HasColumnType("float")
                        .HasColumnName("Year");

                    b.HasKey("ID");

                    b.ToTable("MasterList");
                });
#pragma warning restore 612, 618
        }
    }
}
